repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        language: system
      - id: check-yaml
        name: Check Yaml
        language: system
        types: [yaml]
      - id: end-of-file-fixer
        name: Fix End of Files
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        language: system
        types: [text]
        stages: [commit, push, manual]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
      - id: reorder-python-imports
        name: Reorder python imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--application-directories=custom_components]
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
