name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.13.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
